import React from 'react';
import { FileSpreadsheet, Download } from 'lucide-react';
import StatsCard from '../components/StatsCard';
import RecentActivity from '../components/RecentActivity';
import QuickActions from '../components/QuickActions';

const DashboardPage = () => {
  const generateReport = () => {
    const reportData = {
      generatedAt: new Date().toISOString(),
      summary: {
        totalMembers: 1254,
        activeMembers: 892,
        monthlyRevenue: 24500,
        classesToday: 14
      },
      membershipDistribution: {
        premium: 456,
        basic: 398,
        vip: 38,
        inactive: 362
      },
      revenueBreakdown: {
        memberships: 18500,
        personalTraining: 3200,
        supplements: 1800,
        dayPasses: 1000
      },
      classStatistics: {
        totalClasses: 342,
        averageAttendance: 78,
        mostPopular: 'HIIT Training',
        leastPopular: 'Early Morning Yoga'
      },
      equipmentStatus: {
        operational: 45,
        maintenance: 3,
        outOfOrder: 2
      },
      staffMetrics: {
        totalStaff: 24,
        trainers: 12,
        instructors: 8,
        management: 4
      }
    };

    const reportContent = `
# FitFlow Gym Management Report
Generated on: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}

## Executive Summary
- Total Members: ${reportData.summary.totalMembers}
- Active Members: ${reportData.summary.activeMembers}
- Monthly Revenue: $${reportData.summary.monthlyRevenue.toLocaleString()}
- Classes Today: ${reportData.summary.classesToday}

## Membership Distribution
- Premium Members: ${reportData.membershipDistribution.premium}
- Basic Members: ${reportData.membershipDistribution.basic}
- VIP Members: ${reportData.membershipDistribution.vip}
- Inactive Members: ${reportData.membershipDistribution.inactive}

## Revenue Breakdown
- Membership Fees: $${reportData.revenueBreakdown.memberships.toLocaleString()}
- Personal Training: $${reportData.revenueBreakdown.personalTraining.toLocaleString()}
- Supplement Sales: $${reportData.revenueBreakdown.supplements.toLocaleString()}
- Day Passes: $${reportData.revenueBreakdown.dayPasses.toLocaleString()}

## Class Statistics
- Total Classes This Month: ${reportData.classStatistics.totalClasses}
- Average Attendance Rate: ${reportData.classStatistics.averageAttendance}%
- Most Popular Class: ${reportData.classStatistics.mostPopular}
- Least Popular Class: ${reportData.classStatistics.leastPopular}

## Equipment Status
- Operational Equipment: ${reportData.equipmentStatus.operational}
- Equipment in Maintenance: ${reportData.equipmentStatus.maintenance}
- Out of Order Equipment: ${reportData.equipmentStatus.outOfOrder}

## Staff Metrics
- Total Staff Members: ${reportData.staffMetrics.totalStaff}
- Personal Trainers: ${reportData.staffMetrics.trainers}
- Fitness Instructors: ${reportData.staffMetrics.instructors}
- Management Staff: ${reportData.staffMetrics.management}

## Recommendations
1. Focus on converting inactive members back to active status
2. Increase promotion for least popular classes
3. Schedule maintenance for equipment showing warning signs
4. Consider hiring additional staff during peak hours

---
Report generated by FitFlow Management System
    `;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `FitFlow_Report_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const exportData = () => {
    const gymData = {
      gymInfo: {
        name: 'FitFlow Gym',
        locations: [
          {
            id: 1,
            name: 'FitFlow Downtown',
            address: '123 Main St, Downtown, NY 10001',
            phone: '+1 (555) 123-4567',
            capacity: 500,
            currentMembers: 342,
            operatingHours: '5:00 AM - 11:00 PM'
          },
          {
            id: 2,
            name: 'FitFlow Westside',
            address: '456 West Ave, Westside, NY 10002',
            phone: '+1 (555) 234-5678',
            capacity: 300,
            currentMembers: 198,
            operatingHours: '6:00 AM - 10:00 PM'
          }
        ],
        equipment: [
          { id: 1, name: 'Treadmill Pro X1', type: 'Cardio', status: 'operational' },
          { id: 2, name: 'Elliptical Elite', type: 'Cardio', status: 'maintenance' },
          { id: 3, name: 'Weight Bench Deluxe', type: 'Strength', status: 'operational' }
        ]
      },
      userData: {
        members: [
          {
            id: 1,
            name: 'John Doe',
            email: 'john.doe@email.com',
            phone: '+1 (555) 123-4567',
            membershipType: 'Premium',
            joinDate: '2024-01-15',
            status: 'active'
          },
          {
            id: 2,
            name: 'Sarah Smith',
            email: 'sarah.smith@email.com',
            phone: '+1 (555) 234-5678',
            membershipType: 'Basic',
            joinDate: '2024-02-01',
            status: 'active'
          },
          {
            id: 3,
            name: 'Mike Johnson',
            email: 'mike.johnson@email.com',
            phone: '+1 (555) 345-6789',
            membershipType: 'Premium',
            joinDate: '2023-12-10',
            status: 'inactive'
          }
        ],
        staff: [
          {
            id: 1,
            name: 'Alex Johnson',
            email: 'alex.johnson@fitflow.com',
            role: 'Personal Trainer',
            department: 'Training',
            hireDate: '2023-06-15'
          },
          {
            id: 2,
            name: 'Maria Garcia',
            email: 'maria.garcia@fitflow.com',
            role: 'Fitness Instructor',
            department: 'Classes',
            hireDate: '2023-08-01'
          }
        ]
      }
    };

    const csvContent = `
# GYM DATA
Gym Name,Location,Address,Phone,Capacity,Current Members,Operating Hours
${gymData.gymInfo.locations.map(loc => 
  `"${loc.name}","${loc.address}","${loc.phone}",${loc.capacity},${loc.currentMembers},"${loc.operatingHours}"`
).join('\n')}

# MEMBER DATA
ID,Name,Email,Phone,Membership Type,Join Date,Status
${gymData.userData.members.map(member => 
  `${member.id},"${member.name}","${member.email}","${member.phone}","${member.membershipType}","${member.joinDate}","${member.status}"`
).join('\n')}

# STAFF DATA
ID,Name,Email,Role,Department,Hire Date
${gymData.userData.staff.map(staff => 
  `${staff.id},"${staff.name}","${staff.email}","${staff.role}","${staff.department}","${staff.hireDate}"`
).join('\n')}
    `;

    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `FitFlow_Data_Export_${new Date().toISOString().split('T')[0]}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="container mx-auto px-4 py-8">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8">
        <div className="mb-4 md:mb-0">
          <h1 className="text-3xl font-bold text-gray-900">Dashboard Overview</h1>
          <p className="text-gray-600">Welcome back! Here's what's happening with your gym today.</p>
        </div>
        
        <div className="flex flex-col sm:flex-row gap-3 w-full md:w-auto">
          <button 
            onClick={generateReport}
            className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors font-medium flex items-center justify-center gap-2"
          >
            <Download className="w-4 h-4" />
            <span>Generate Report</span>
          </button>
          <button 
            onClick={exportData}
            className="px-4 py-2 bg-white text-gray-700 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors font-medium flex items-center justify-center gap-2"
          >
            <FileSpreadsheet className="w-4 h-4" />
            <span>Export Data</span>
          </button>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
        <StatsCard
          title="Total Members"
          value="1,254"
          change="+12% from last month"
          changeType="positive"
        />
        <StatsCard
          title="Active Members"
          value="892"
          change="+5% from last month"
          changeType="positive"
        />
        <StatsCard
          title="Monthly Revenue"
          value="$24,500"
          change="+8% from last month"
          changeType="positive"
        />
        <StatsCard
          title="Classes Today"
          value="14"
          change="-2 from last month"
          changeType="negative"
        />
      </div>

      {/* Main Content Area */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-6">
          <RecentActivity />
          {/* Additional components can be added here */}
        </div>
        
        <div className="space-y-6">
          <QuickActions />
          {/* <EquipmentStatus /> */}
          {/* Additional sidebar components can be added here */}
        </div>
      </div>
    </div>
  );
};

export default DashboardPage;